name: Hyperexecute-Playwright
on:
  workflow_dispatch:
  
jobs:
  HyperExecute-dotnet-Playwright:
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
          chmod +x hyperexecute
          ./hyperexecute --user ${{ secrets.username }} --key ${{ secrets.accesskey }} --download-artifacts --config yaml/dotnet_playwright_hyperexecute_autosplit_sample.yaml
          echo "Test completion"
