name: test
on:
  schedule:
    - cron: '30 5,12 * * *'
  workflow_dispatch:
  
jobs:
  HyperExecute-dotnet-Playwright:
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.1'
    - run: dotnet --version
